FROM python:3.9-slim-buster

WORKDIR /app

COPY ./cbf-backend/requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

COPY ./cbf-backend/ .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]