name: Sample 2 Workflow

on:
  workflow_run:
    workflows: ["Sample 1 Workflow"]
    types:
      - completed
    branches:
      - testing-github-actions # Keep this for direct pushes
      - main                   # <<< ADD THIS LINE! This will catch runs of Sample 1 that are part of a PR to 'main'.

jobs:
  sample2_job:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} 
    # This condition correctly ensures sample1 succeeded.
    runs-on: ubuntu-latest
    steps:
      - name: Echo Sample 2
        run: echo "Thi